name: codeforecon
channels:
  - conda-forge
dependencies:
  - jupyter
  - numpy
  - pandas>=2.1.0
  - pip
  - python=3.10
  - matplotlib
  - pyyaml
  - scipy
  - seaborn
  - statsmodels
  - yaml
  - pyarrow
  - geopandas
  - geoplot
  - nltk
  - arrow
  - osmnx
  - pandas-datareader
  - pandasdmx
  - pdfminer.six
  - jupyter-book
  - pytest
  - rich
  - pyinstrument
  - loguru
  - pre-commit
  - pandera
  - sympy
  - pingouin
  - plotly
  - spacy
  - plotnine
  - altair
  - cerberus
  - great-expectations>=0.17.14
  - waterfallcharts
  - matplotlib-venn
  - pywaffle
  - joypy
  - jupyterlab
  - textstat
  - nbstripout
  - vega_datasets
  - ghp-import
  - colorcet
  - requests-cache
  - pip
  - arch-py
  - workalendar
  - wordcloud
  - bambi
  - pdftotext
  - bottleneck
  - openpyxl
  - python-slugify
  - pymc
  - umap-learn
  - python-dotenv
  - ruff
  - pip:
    - specification_curve
    - stargazer
    - matplotlib-scalebar
    - black-nb
    - skimpy
    - graphviz
    - ruptures
    - sqlmodel
    - ibis-framework
    - binsreg
    - feature-engine
    - lets-plot
    - palmerpenguins
    - pyfixest
    - watermark
